# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 19.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Find the friggin package-lock.json file
      id: find-lock-file
      shell: bash
      run: cd /home/runner ; find . -name package-lock.json -exec ls -l {} \;
    - name: Find the friggin package.json file
      id: find-package-file
      shell: bash
      run: cd /home/runner/work ; find . -name package.json -exec ls -l {} \;
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        ## cache: 'npm'
        ## cache-dependency-path: '/home/runner/work/github-actions-for-ci-cd/Ch02/02_03_ci_for_javascript/package-lock.json'
        ## cache-dependency-path: '/home/runner/work/github-actions-for-ci-cd/github-actions-for-ci-cd'
    - name: Get npm cache dir
      id: npm-cache-dir
      shell: bash
      run:  echo "dir=$(npm config get cache)" ; echo "cache:$dir"
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
